/* ============================================================
   THE OPEN CHAMPIONSHIP POOL - GOLFER ROSTER (source of truth)
   Royal Birkdale, July 16-19, 2026
   ------------------------------------------------------------
   Full field. Amateurs flagged with amateur: true.
   Tiers assigned by current tournament odds/form (July 2026):
   Tier 1 (5)  - outright favorites, shortest odds
   Tier 2 (15) - top contenders
   Tier 3 (35) - solid mid-field with winning chances
   Tier 4 (45) - journeymen / longer-shot tour pros
   Tier 5 (55) - deep field, longshots, and amateurs
   odds left null - fill in from a live sportsbook if wanted;
   the dropdown displays tier regardless of whether odds is set.
   NOTE: no template literals anywhere in this codebase by
   design - string concatenation only.
   ============================================================ */

var GOLFERS = [
  { name: "Ludvig Aberg", tier: 2, odds: null, amateur: false },
  { name: "Angel Ayora", tier: 5, odds: null, amateur: false },
  { name: "Sam Bairstow", tier: 5, odds: null, amateur: false },
  { name: "Matthew Baldwin", tier: 4, odds: null, amateur: false },
  { name: "Jose Luis Ballester Barrio", tier: 5, odds: null, amateur: false },
  { name: "Daniel Berger", tier: 4, odds: null, amateur: false },
  { name: "Akshay Bhatia", tier: 4, odds: null, amateur: false },
  { name: "Dan Bradbury", tier: 4, odds: null, amateur: false },
  { name: "Keegan Bradley", tier: 3, odds: null, amateur: false },
  { name: "Michael Brennan", tier: 4, odds: null, amateur: false },
  { name: "Jacob Bridgeman", tier: 4, odds: null, amateur: false },
  { name: "Daniel Brown", tier: 4, odds: null, amateur: false },
  { name: "Jack Buchanan", tier: 5, odds: null, amateur: true },
  { name: "Sam Burns", tier: 3, odds: null, amateur: false },
  { name: "Laurie Canter", tier: 3, odds: null, amateur: false },
  { name: "Patrick Cantlay", tier: 2, odds: null, amateur: false },
  { name: "Bud Cauley", tier: 4, odds: null, amateur: false },
  { name: "Eugenio Chacarra", tier: 4, odds: null, amateur: false },
  { name: "Tiger Christensen", tier: 5, odds: null, amateur: false },
  { name: "Stewart Cink", tier: 4, odds: null, amateur: false },
  { name: "Wyndham Clark", tier: 3, odds: null, amateur: false },
  { name: "Darren Clarke", tier: 4, odds: null, amateur: false },
  { name: "Eric Cole", tier: 4, odds: null, amateur: false },
  { name: "Corey Conners", tier: 3, odds: null, amateur: false },
  { name: "Pierceson Coody", tier: 4, odds: null, amateur: false },
  { name: "Martin Couvra", tier: 5, odds: null, amateur: false },
  { name: "MJ Daffue", tier: 4, odds: null, amateur: false },
  { name: "Jason Day", tier: 4, odds: null, amateur: false },
  { name: "Alejandro De Castro Piera", tier: 5, odds: null, amateur: true },
  { name: "Bryson DeChambeau", tier: 3, odds: null, amateur: false },
  { name: "Thomas Detry", tier: 3, odds: null, amateur: false },
  { name: "Alistair Docherty", tier: 5, odds: null, amateur: false },
  { name: "Hennie du Plessis", tier: 5, odds: null, amateur: false },
  { name: "David Duval", tier: 5, odds: null, amateur: false },
  { name: "Nico Echavarria", tier: 4, odds: null, amateur: false },
  { name: "Harris English", tier: 3, odds: null, amateur: false },
  { name: "Matt Fitzpatrick", tier: 1, odds: null, amateur: false },
  { name: "Alex Fitzpatrick", tier: 3, odds: null, amateur: false },
  { name: "Tommy Fleetwood", tier: 1, odds: null, amateur: false },
  { name: "Rickie Fowler", tier: 3, odds: null, amateur: false },
  { name: "Ryan Fox", tier: 4, odds: null, amateur: false },
  { name: "Ryan Gerard", tier: 5, odds: null, amateur: false },
  { name: "Chris Gotterup", tier: 2, odds: null, amateur: false },
  { name: "Stuart Grehan", tier: 5, odds: null, amateur: true },
  { name: "Max Greyserman", tier: 5, odds: null, amateur: false },
  { name: "Ben Griffin", tier: 4, odds: null, amateur: false },
  { name: "Lev Grinberg", tier: 5, odds: null, amateur: true },
  { name: "Harry Hall", tier: 4, odds: null, amateur: false },
  { name: "Jeongwoo Ham", tier: 4, odds: null, amateur: false },
  { name: "Brian Harman", tier: 3, odds: null, amateur: false },
  { name: "Padraig Harrington", tier: 4, odds: null, amateur: false },
  { name: "Tyrrell Hatton", tier: 2, odds: null, amateur: false },
  { name: "Russell Henley", tier: 3, odds: null, amateur: false },
  { name: "Lucas Herbert", tier: 4, odds: null, amateur: false },
  { name: "Kazuki Higa", tier: 5, odds: null, amateur: false },
  { name: "Daniel Hillier", tier: 5, odds: null, amateur: false },
  { name: "Ryo Hisatsune", tier: 5, odds: null, amateur: false },
  { name: "Nicolai Hojgaard", tier: 3, odds: null, amateur: false },
  { name: "Rasmus Hojgaard", tier: 3, odds: null, amateur: false },
  { name: "Michael Hollick", tier: 5, odds: null, amateur: false },
  { name: "Max Homa", tier: 3, odds: null, amateur: false },
  { name: "Billy Horschel", tier: 3, odds: null, amateur: false },
  { name: "Viktor Hovland", tier: 2, odds: null, amateur: false },
  { name: "David Howard", tier: 5, odds: null, amateur: true },
  { name: "Mason Howell", tier: 5, odds: null, amateur: true },
  { name: "Sungjae Im", tier: 2, odds: null, amateur: false },
  { name: "Casey Jarvis", tier: 5, odds: null, amateur: false },
  { name: "Cameron John", tier: 5, odds: null, amateur: false },
  { name: "Matthew Jordan", tier: 5, odds: null, amateur: false },
  { name: "Kota Kaneko", tier: 5, odds: null, amateur: false },
  { name: "Naoyuki Kataoka", tier: 5, odds: null, amateur: false },
  { name: "Johnny Keefer", tier: 5, odds: null, amateur: false },
  { name: "Si Woo Kim", tier: 3, odds: null, amateur: false },
  { name: "Tom Kim", tier: 2, odds: null, amateur: false },
  { name: "Michael Kim", tier: 4, odds: null, amateur: false },
  { name: "Kurt Kitayama", tier: 4, odds: null, amateur: false },
  { name: "Jake Knapp", tier: 4, odds: null, amateur: false },
  { name: "Kazuma Kobori", tier: 4, odds: null, amateur: false },
  { name: "Brooks Koepka", tier: 3, odds: null, amateur: false },
  { name: "Frederic Lacroix", tier: 5, odds: null, amateur: false },
  { name: "Joakim Lagergren", tier: 5, odds: null, amateur: false },
  { name: "Fifa Laopakdee", tier: 5, odds: null, amateur: true },
  { name: "Francesco Laporta", tier: 4, odds: null, amateur: false },
  { name: "Min Woo Lee", tier: 2, odds: null, amateur: false },
  { name: "Haotong Li", tier: 4, odds: null, amateur: false },
  { name: "Shane Lowry", tier: 2, odds: null, amateur: false },
  { name: "Robert MacIntyre", tier: 2, odds: null, amateur: false },
  { name: "Hideki Matsuyama", tier: 3, odds: null, amateur: false },
  { name: "Matt McCarty", tier: 4, odds: null, amateur: false },
  { name: "Jack McDonald", tier: 5, odds: null, amateur: false },
  { name: "Rory McIlroy", tier: 1, odds: null, amateur: false },
  { name: "Tom McKibbin", tier: 3, odds: null, amateur: false },
  { name: "Maverick McNealy", tier: 4, odds: null, amateur: false },
  { name: "Keith Mitchell", tier: 4, odds: null, amateur: false },
  { name: "Francesco Molinari", tier: 4, odds: null, amateur: false },
  { name: "Collin Morikawa", tier: 2, odds: null, amateur: false },
  { name: "Ryutaro Nagano", tier: 5, odds: null, amateur: false },
  { name: "Keita Nakajima", tier: 5, odds: null, amateur: false },
  { name: "Rasmus Neergaard-Petersen", tier: 5, odds: null, amateur: false },
  { name: "James Nicholas", tier: 5, odds: null, amateur: false },
  { name: "Joaquin Niemann", tier: 2, odds: null, amateur: false },
  { name: "Alex Noren", tier: 3, odds: null, amateur: false },
  { name: "Shaun Norris", tier: 5, odds: null, amateur: false },
  { name: "Andrew Novak", tier: 4, odds: null, amateur: false },
  { name: "Louis Oosthuizen", tier: 3, odds: null, amateur: false },
  { name: "John Parry", tier: 5, odds: null, amateur: false },
  { name: "Marco Penge", tier: 3, odds: null, amateur: false },
  { name: "Victor Perez", tier: 4, odds: null, amateur: false },
  { name: "Marcus Plunkett", tier: 5, odds: null, amateur: false },
  { name: "JT Poston", tier: 3, odds: null, amateur: false },
  { name: "David Puig", tier: 4, odds: null, amateur: false },
  { name: "Mateo Pulcini", tier: 5, odds: null, amateur: true },
  { name: "Jon Rahm", tier: 1, odds: null, amateur: false },
  { name: "Aaron Rai", tier: 3, odds: null, amateur: false },
  { name: "Patrick Reed", tier: 3, odds: null, amateur: false },
  { name: "Kristoffer Reitan", tier: 4, odds: null, amateur: false },
  { name: "Justin Rose", tier: 2, odds: null, amateur: false },
  { name: "Antoine Rozner", tier: 4, odds: null, amateur: false },
  { name: "Nevill Ruiter", tier: 5, odds: null, amateur: true },
  { name: "Adrien Saddier", tier: 5, odds: null, amateur: false },
  { name: "Jayden Schaper", tier: 5, odds: null, amateur: false },
  { name: "Xander Schauffele", tier: 2, odds: null, amateur: false },
  { name: "Scottie Scheffler", tier: 1, odds: null, amateur: false },
  { name: "Adam Scott", tier: 3, odds: null, amateur: false },
  { name: "Baard Bjoernevik Skogen", tier: 5, odds: null, amateur: false },
  { name: "Tom Sloman", tier: 5, odds: null, amateur: false },
  { name: "Alex Smalley", tier: 5, odds: null, amateur: false },
  { name: "Cameron Smith", tier: 3, odds: null, amateur: false },
  { name: "Jordan Smith", tier: 4, odds: null, amateur: false },
  { name: "Travis Smyth", tier: 5, odds: null, amateur: false },
  { name: "Matthew Southgate", tier: 5, odds: null, amateur: false },
  { name: "J.J. Spaun", tier: 3, odds: null, amateur: false },
  { name: "Jordan Spieth", tier: 3, odds: null, amateur: false },
  { name: "Henrik Stenson", tier: 4, odds: null, amateur: false },
  { name: "Sam Stevens", tier: 4, odds: null, amateur: false },
  { name: "Sepp Straka", tier: 2, odds: null, amateur: false },
  { name: "Jackson Suber", tier: 5, odds: null, amateur: false },
  { name: "Andy Sullivan", tier: 4, odds: null, amateur: false },
  { name: "Caleb Surratt", tier: 4, odds: null, amateur: false },
  { name: "Jesper Svensson", tier: 5, odds: null, amateur: false },
  { name: "Nick Taylor", tier: 3, odds: null, amateur: false },
  { name: "Sahith Theegala", tier: 3, odds: null, amateur: false },
  { name: "Justin Thomas", tier: 3, odds: null, amateur: false },
  { name: "Michael Thorbjornsen", tier: 4, odds: null, amateur: false },
  { name: "Austen Truslow", tier: 5, odds: null, amateur: false },
  { name: "Peter Uihlein", tier: 5, odds: null, amateur: false },
  { name: "Sami Valimaki", tier: 5, odds: null, amateur: false },
  { name: "Scott Vincent", tier: 5, odds: null, amateur: false },
  { name: "Matt Wallace", tier: 3, odds: null, amateur: false },
  { name: "Tim Wiedemeyer", tier: 5, odds: null, amateur: true },
  { name: "Bernd Wiesberger", tier: 4, odds: null, amateur: false },
  { name: "Gary Woodland", tier: 4, odds: null, amateur: false },
  { name: "Jiho Yang", tier: 5, odds: null, amateur: false },
  { name: "Ren Yonezawa", tier: 5, odds: null, amateur: false },
  { name: "Cameron Young", tier: 3, odds: null, amateur: false }
];

/* Node export for testing; harmless in browser */
if (typeof module !== "undefined" && module.exports) {
  module.exports = { GOLFERS: GOLFERS };
}
