/* ============================================================
   THE OPEN CHAMPIONSHIP POOL - GOLFER ROSTER (source of truth)
   Royal Birkdale, July 16-19, 2026
   ------------------------------------------------------------
   Full field. Amateurs flagged with amateur: true.
   tier / odds: fill in when odds-band tiers are finalized.
   NOTE: no template literals anywhere in this codebase by
   design - string concatenation only.
   ============================================================ */

var GOLFERS = [
  { name: "Ludvig Aberg", tier: null, odds: null, amateur: false },
  { name: "Angel Ayora", tier: null, odds: null, amateur: false },
  { name: "Sam Bairstow", tier: null, odds: null, amateur: false },
  { name: "Matthew Baldwin", tier: null, odds: null, amateur: false },
  { name: "Jose Luis Ballester Barrio", tier: null, odds: null, amateur: false },
  { name: "Daniel Berger", tier: null, odds: null, amateur: false },
  { name: "Akshay Bhatia", tier: null, odds: null, amateur: false },
  { name: "Dan Bradbury", tier: null, odds: null, amateur: false },
  { name: "Keegan Bradley", tier: null, odds: null, amateur: false },
  { name: "Michael Brennan", tier: null, odds: null, amateur: false },
  { name: "Jacob Bridgeman", tier: null, odds: null, amateur: false },
  { name: "Daniel Brown", tier: null, odds: null, amateur: false },
  { name: "Jack Buchanan", tier: null, odds: null, amateur: true },
  { name: "Sam Burns", tier: null, odds: null, amateur: false },
  { name: "Laurie Canter", tier: null, odds: null, amateur: false },
  { name: "Patrick Cantlay", tier: null, odds: null, amateur: false },
  { name: "Bud Cauley", tier: null, odds: null, amateur: false },
  { name: "Eugenio Chacarra", tier: null, odds: null, amateur: false },
  { name: "Tiger Christensen", tier: null, odds: null, amateur: false },
  { name: "Stewart Cink", tier: null, odds: null, amateur: false },
  { name: "Wyndham Clark", tier: null, odds: null, amateur: false },
  { name: "Darren Clarke", tier: null, odds: null, amateur: false },
  { name: "Eric Cole", tier: null, odds: null, amateur: false },
  { name: "Corey Conners", tier: null, odds: null, amateur: false },
  { name: "Pierceson Coody", tier: null, odds: null, amateur: false },
  { name: "Martin Couvra", tier: null, odds: null, amateur: false },
  { name: "MJ Daffue", tier: null, odds: null, amateur: false },
  { name: "Jason Day", tier: null, odds: null, amateur: false },
  { name: "Alejandro De Castro Piera", tier: null, odds: null, amateur: true },
  { name: "Bryson DeChambeau", tier: null, odds: null, amateur: false },
  { name: "Thomas Detry", tier: null, odds: null, amateur: false },
  { name: "Alistair Docherty", tier: null, odds: null, amateur: false },
  { name: "Hennie du Plessis", tier: null, odds: null, amateur: false },
  { name: "David Duval", tier: null, odds: null, amateur: false },
  { name: "Nico Echavarria", tier: null, odds: null, amateur: false },
  { name: "Harris English", tier: null, odds: null, amateur: false },
  { name: "Matt Fitzpatrick", tier: null, odds: null, amateur: false },
  { name: "Alex Fitzpatrick", tier: null, odds: null, amateur: false },
  { name: "Tommy Fleetwood", tier: null, odds: null, amateur: false },
  { name: "Rickie Fowler", tier: null, odds: null, amateur: false },
  { name: "Ryan Fox", tier: null, odds: null, amateur: false },
  { name: "Ryan Gerard", tier: null, odds: null, amateur: false },
  { name: "Chris Gotterup", tier: null, odds: null, amateur: false },
  { name: "Stuart Grehan", tier: null, odds: null, amateur: true },
  { name: "Max Greyserman", tier: null, odds: null, amateur: false },
  { name: "Ben Griffin", tier: null, odds: null, amateur: false },
  { name: "Lev Grinberg", tier: null, odds: null, amateur: true },
  { name: "Harry Hall", tier: null, odds: null, amateur: false },
  { name: "Jeongwoo Ham", tier: null, odds: null, amateur: false },
  { name: "Brian Harman", tier: null, odds: null, amateur: false },
  { name: "Padraig Harrington", tier: null, odds: null, amateur: false },
  { name: "Tyrrell Hatton", tier: null, odds: null, amateur: false },
  { name: "Russell Henley", tier: null, odds: null, amateur: false },
  { name: "Lucas Herbert", tier: null, odds: null, amateur: false },
  { name: "Kazuki Higa", tier: null, odds: null, amateur: false },
  { name: "Daniel Hillier", tier: null, odds: null, amateur: false },
  { name: "Ryo Hisatsune", tier: null, odds: null, amateur: false },
  { name: "Nicolai Hojgaard", tier: null, odds: null, amateur: false },
  { name: "Rasmus Hojgaard", tier: null, odds: null, amateur: false },
  { name: "Michael Hollick", tier: null, odds: null, amateur: false },
  { name: "Max Homa", tier: null, odds: null, amateur: false },
  { name: "Billy Horschel", tier: null, odds: null, amateur: false },
  { name: "Viktor Hovland", tier: null, odds: null, amateur: false },
  { name: "David Howard", tier: null, odds: null, amateur: true },
  { name: "Mason Howell", tier: null, odds: null, amateur: true },
  { name: "Sungjae Im", tier: null, odds: null, amateur: false },
  { name: "Casey Jarvis", tier: null, odds: null, amateur: false },
  { name: "Cameron John", tier: null, odds: null, amateur: false },
  { name: "Matthew Jordan", tier: null, odds: null, amateur: false },
  { name: "Kota Kaneko", tier: null, odds: null, amateur: false },
  { name: "Naoyuki Kataoka", tier: null, odds: null, amateur: false },
  { name: "Johnny Keefer", tier: null, odds: null, amateur: false },
  { name: "Si Woo Kim", tier: null, odds: null, amateur: false },
  { name: "Tom Kim", tier: null, odds: null, amateur: false },
  { name: "Michael Kim", tier: null, odds: null, amateur: false },
  { name: "Kurt Kitayama", tier: null, odds: null, amateur: false },
  { name: "Jake Knapp", tier: null, odds: null, amateur: false },
  { name: "Kazuma Kobori", tier: null, odds: null, amateur: false },
  { name: "Brooks Koepka", tier: null, odds: null, amateur: false },
  { name: "Frederic Lacroix", tier: null, odds: null, amateur: false },
  { name: "Joakim Lagergren", tier: null, odds: null, amateur: false },
  { name: "Fifa Laopakdee", tier: null, odds: null, amateur: true },
  { name: "Francesco Laporta", tier: null, odds: null, amateur: false },
  { name: "Min Woo Lee", tier: null, odds: null, amateur: false },
  { name: "Haotong Li", tier: null, odds: null, amateur: false },
  { name: "Shane Lowry", tier: null, odds: null, amateur: false },
  { name: "Robert MacIntyre", tier: null, odds: null, amateur: false },
  { name: "Hideki Matsuyama", tier: null, odds: null, amateur: false },
  { name: "Matt McCarty", tier: null, odds: null, amateur: false },
  { name: "Jack McDonald", tier: null, odds: null, amateur: false },
  { name: "Rory McIlroy", tier: null, odds: null, amateur: false },
  { name: "Tom McKibbin", tier: null, odds: null, amateur: false },
  { name: "Maverick McNealy", tier: null, odds: null, amateur: false },
  { name: "Keith Mitchell", tier: null, odds: null, amateur: false },
  { name: "Francesco Molinari", tier: null, odds: null, amateur: false },
  { name: "Collin Morikawa", tier: null, odds: null, amateur: false },
  { name: "Ryutaro Nagano", tier: null, odds: null, amateur: false },
  { name: "Keita Nakajima", tier: null, odds: null, amateur: false },
  { name: "Rasmus Neergaard-Petersen", tier: null, odds: null, amateur: false },
  { name: "James Nicholas", tier: null, odds: null, amateur: false },
  { name: "Joaquin Niemann", tier: null, odds: null, amateur: false },
  { name: "Alex Noren", tier: null, odds: null, amateur: false },
  { name: "Shaun Norris", tier: null, odds: null, amateur: false },
  { name: "Andrew Novak", tier: null, odds: null, amateur: false },
  { name: "Louis Oosthuizen", tier: null, odds: null, amateur: false },
  { name: "John Parry", tier: null, odds: null, amateur: false },
  { name: "Marco Penge", tier: null, odds: null, amateur: false },
  { name: "Victor Perez", tier: null, odds: null, amateur: false },
  { name: "Marcus Plunkett", tier: null, odds: null, amateur: false },
  { name: "JT Poston", tier: null, odds: null, amateur: false },
  { name: "David Puig", tier: null, odds: null, amateur: false },
  { name: "Mateo Pulcini", tier: null, odds: null, amateur: true },
  { name: "Jon Rahm", tier: null, odds: null, amateur: false },
  { name: "Aaron Rai", tier: null, odds: null, amateur: false },
  { name: "Patrick Reed", tier: null, odds: null, amateur: false },
  { name: "Kristoffer Reitan", tier: null, odds: null, amateur: false },
  { name: "Justin Rose", tier: null, odds: null, amateur: false },
  { name: "Antoine Rozner", tier: null, odds: null, amateur: false },
  { name: "Nevill Ruiter", tier: null, odds: null, amateur: true },
  { name: "Adrien Saddier", tier: null, odds: null, amateur: false },
  { name: "Jayden Schaper", tier: null, odds: null, amateur: false },
  { name: "Xander Schauffele", tier: null, odds: null, amateur: false },
  { name: "Scottie Scheffler", tier: null, odds: null, amateur: false },
  { name: "Adam Scott", tier: null, odds: null, amateur: false },
  { name: "Baard Bjoernevik Skogen", tier: null, odds: null, amateur: false },
  { name: "Tom Sloman", tier: null, odds: null, amateur: false },
  { name: "Alex Smalley", tier: null, odds: null, amateur: false },
  { name: "Cameron Smith", tier: null, odds: null, amateur: false },
  { name: "Jordan Smith", tier: null, odds: null, amateur: false },
  { name: "Travis Smyth", tier: null, odds: null, amateur: false },
  { name: "Matthew Southgate", tier: null, odds: null, amateur: false },
  { name: "J.J. Spaun", tier: null, odds: null, amateur: false },
  { name: "Jordan Spieth", tier: null, odds: null, amateur: false },
  { name: "Henrik Stenson", tier: null, odds: null, amateur: false },
  { name: "Sam Stevens", tier: null, odds: null, amateur: false },
  { name: "Sepp Straka", tier: null, odds: null, amateur: false },
  { name: "Jackson Suber", tier: null, odds: null, amateur: false },
  { name: "Andy Sullivan", tier: null, odds: null, amateur: false },
  { name: "Caleb Surratt", tier: null, odds: null, amateur: false },
  { name: "Jesper Svensson", tier: null, odds: null, amateur: false },
  { name: "Nick Taylor", tier: null, odds: null, amateur: false },
  { name: "Sahith Theegala", tier: null, odds: null, amateur: false },
  { name: "Justin Thomas", tier: null, odds: null, amateur: false },
  { name: "Michael Thorbjornsen", tier: null, odds: null, amateur: false },
  { name: "Austen Truslow", tier: null, odds: null, amateur: false },
  { name: "Peter Uihlein", tier: null, odds: null, amateur: false },
  { name: "Sami Valimaki", tier: null, odds: null, amateur: false },
  { name: "Scott Vincent", tier: null, odds: null, amateur: false },
  { name: "Matt Wallace", tier: null, odds: null, amateur: false },
  { name: "Tim Wiedemeyer", tier: null, odds: null, amateur: true },
  { name: "Bernd Wiesberger", tier: null, odds: null, amateur: false },
  { name: "Gary Woodland", tier: null, odds: null, amateur: false },
  { name: "Jiho Yang", tier: null, odds: null, amateur: false },
  { name: "Ren Yonezawa", tier: null, odds: null, amateur: false },
  { name: "Cameron Young", tier: null, odds: null, amateur: false }
];

/* Node export for testing; harmless in browser */
if (typeof module !== "undefined" && module.exports) {
  module.exports = { GOLFERS: GOLFERS };
}
